drop table PAYMENT;
drop table ORDERITEM;
drop table "ORDER";
drop table USERCARTPRODUCTS;
drop table PRODUCT;
drop table USERS;
drop table "ROLE";

CREATE TABLE "ROLE"
    (
    "ROLEID" INT NOT NULL,
    "NAME" VARCHAR(20) NOT NULL,
    PRIMARY KEY ("ROLEID")
    );

CREATE TABLE USERS
    (
    "USERID" INT NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    "ROLEID" INT NOT NULL,
    "FIRSTNAME" VARCHAR(20) NOT NULL,
    "LASTNAME" VARCHAR(20) NOT NULL,
    "EMAIL" VARCHAR(60) NOT NULL,
    "PASSWORD" VARCHAR(20) NOT NULL,
    "ADDRESS" VARCHAR(60),
    PRIMARY KEY ("USERID"),
    FOREIGN KEY ("ROLEID") REFERENCES ROLE(ROLEID));

CREATE TABLE PRODUCT
    (
    "PRODUCTID" INT NOT NULL,
    "NAME" VARCHAR(40) NOT NULL,
    "DESCRIPTION" VARCHAR(200) NOT NULL,
    "STOCKQUANTITY" INT NOT NULL,
    "PRICE" FLOAT NOT NULL,
    PRIMARY KEY ("PRODUCTID")
    );

CREATE TABLE USERCARTPRODUCTS
    (
    "USERCARTPRODUCTID" INT NOT NULL,
    "USERID" INT NOT NULL,
    "PRODUCTID" INT NOT NULL,
    "QUANTITY" INT NOT NULL,
    PRIMARY KEY (USERCARTPRODUCTID),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID),
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(PRODUCTID)
    );

CREATE TABLE "ORDER"
    (
    "ORDERID" INT NOT NULL, 
    "USERID" INT NOT NULL,
    "ORDERNUMBER" VARCHAR(40) NOT NULL,
    "CREATEDON" DATE NOT NULL,
    PRIMARY KEY ("ORDERID"),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID)
    );

CREATE TABLE ORDERITEM
    (
    "ORDERITEMID" INT NOT NULL,
    "ORDERID" INT NOT NULL,
    "PRODUCTID" INT NOT NULL, 
    "QUANTITY" INT NOT NULL,
    "PRICEPERUNIT" FLOAT NOT NULL,
    PRIMARY KEY (ORDERITEMID),
    FOREIGN KEY (ORDERID) REFERENCES "ORDER"(ORDERID),
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(PRODUCTID)
    );

CREATE TABLE PAYMENT
    (
    "PAYMENTID" INT NOT NULL,
    "PAIDAMOUNT" FLOAT NOT NULL,
    "DETAIL" VARCHAR(100) NOT NULL,
    PRIMARY KEY (PAYMENTID)
    );
